<?php

return [
    'dashboard-view-path'       => 'Cms::admin.dashboard',
    'upload_path'               => public_path('uploads'),
    'thumb_path'                => public_path('uploads/thumbs'),

    'providers' => [
        \Ixudra\Curl\CurlServiceProvider::class,
        \Collective\Html\HtmlServiceProvider::class,
        \Intervention\Image\ImageServiceProvider::class,
        \Packages\Appearance\Providers\ModuleServiceProvider::class,
        \Packages\Appearance\Providers\RoutingServiceProvider::class,
        \Packages\Cms\Providers\RoutingServiceProvider::class,
        \Packages\News\Providers\ModuleServiceProvider::class,
        \Packages\News\Providers\RoutingServiceProvider::class,
        \Packages\Page\Providers\ModuleServiceProvider::class,
        \Packages\Page\Providers\RoutingServiceProvider::class,
        \Packages\FbComment\Providers\ModuleServiceProvider::class,
        \Packages\FbComment\Providers\RoutingServiceProvider::class,
        \Packages\CmsInstall\Providers\ModuleServiceProvider::class,
        \Packages\CmsInstall\Providers\RoutingServiceProvider::class,
    ],

    'aliases' => [
        'Form'              =>  \Collective\Html\FormFacade::class,
        'Html'              =>  \Collective\Html\HtmlFacade::class,
        'AccessControl'     =>  \Packages\Cms\Support\Facades\AccessControl::class,
        'AdminController'   =>  \Packages\Cms\Http\Controllers\Admin\AdminController::class,
        'AdminMenu'         =>  \Packages\Cms\Support\Facades\AdminMenu::class,
        'Contact'           =>  \Packages\Cms\Support\Facades\Contact::class,
        'Module'            =>  \Packages\Cms\Support\Facades\Module::class,
        'Setting'           =>  \Packages\Cms\Support\Facades\Setting::class,
        'Widget'            =>  \Packages\Cms\Support\Facades\Widget::class,
        'HomeController'    =>  \Packages\Cms\Http\Controllers\HomeController::class,
        'AppController'     =>  \Packages\Cms\Http\Controllers\AppController::class,
        'ApiController'     =>  \Packages\Cms\Http\Controllers\ApiController::class,
        'Language'          =>  \Packages\Cms\Support\Facades\Language::class,
        'Curl'              =>  \Ixudra\Curl\Facades\Curl::class,
        'Menu'              =>  \Packages\Appearance\Support\Facades\Menu::class,
        'Action'            =>  \Packages\Cms\Support\Facades\Action::class,
        'Filter'            =>  \Packages\Cms\Support\Facades\Filter::class,
        'Metatag'           =>  \Packages\Cms\Support\Facades\Metatag::class,
        'Asset'             =>  \Packages\Cms\Support\Facades\Asset::class,
        'Image'             =>  \Intervention\Image\Facades\Image::class,
        'FbComment'         =>  \Packages\FbComment\Support\Facades\Comment::class,
    ],

    'consoles' => [
        \Packages\Cms\Console\Generators\MakeModule::class,
        \Packages\Cms\Console\Generators\MakeProvider::class,
        \Packages\Cms\Console\Generators\MakeController::class,
        \Packages\Cms\Console\Generators\MakeMiddleware::class,
        \Packages\Cms\Console\Generators\MakeRequest::class,
        \Packages\Cms\Console\Generators\MakeModel::class,
        \Packages\Cms\Console\Generators\MakeFacade::class,
        \Packages\Cms\Console\Generators\MakeService::class,
        \Packages\Cms\Console\Generators\MakeSupport::class,
        \Packages\Cms\Console\Generators\MakeMigration::class,
        \Packages\Cms\Console\Generators\MakeCommand::class,
        \Packages\Cms\Console\Generators\MakeWidget::class,
    ],
];
